Avoid conflicts with distutils
The error

setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple")

seems to be caused by a conflict between setuptools and distutils.

It's unclear why that error shows up but maybe dropping distutils here
helps.